### ISSUE TITLE
[TRACKER] Requirement Documentation

### ISSUE THREAD

**Issue by Spartan322** [OpenVicProject/OpenVic#27]
This is to track the requirements that have been done, either entirely or partially but have not been documented on the repository yet:

- [x] #28
- [x] #29
- [x] #30
- [x] #31
- [x] #32
- [x] #34
- [x] #35
- [x] #36
- [x] #37
- [x] #38
- [x] #39
- [x] #40
- [x] #41
- [x] #42

**Comment by BrickPi** [comment]
@Spartan322 stale & superseded, should probably close if you don't have any issues

**Comment by Spartan322** [comment]
This issue should remain open as its a tracker issue but #33 can be closed because it is faulty to consider right now.

**Comment by valahdev** [comment]
Requirements are no longer used, as the team has shifted towards tasking.
